name = "Junimo"
uuid = "3d54b6d4-9b4d-4421-9513-a6007c061c41"
authors = ["cug-xyx <xieyuxuan0430@igsnrr.ac.cn>"]
version = "0.1.2"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CSV = "0.10.15"
CairoMakie = "0.15.8"
DataFrames = "1.8.1"
Random = "1.11.0"
Statistics = "1.11.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
