name = "Junimo"
uuid = "3d54b6d4-9b4d-4421-9513-a6007c061c41"
authors = ["cug-xyx <xieyx0430@igsnrr.ac.cn>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Random = "1.11.0"
