[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Junimo = "3d54b6d4-9b4d-4421-9513-a6007c061c41"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
